- hosts: localhost
  tasks:
    - import_role:
        name: Aws_services
    - name: Run tasks/specific task instead of 'main'
      import_role:
        name: Aws_services
        tasks_from: create_ec2
