---
- name: Launch instance
  ec2:
    key_name: "{{ keypair }}"
    group: "{{ security_group }}"
    instance_type: "{{ instance_type }}"
    image: "{{ image }}"
    wait: true
    region: "{{ region }}"
    vpc_subnet_id: "{{ vpc_subnet_id }}"
    instance_tags:
      Name: NewInstance
    assign_public_ip: yes
  register: ec2
